/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

/**
 *
 * @author Aleksa
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNastup = new javax.swing.JMenu();
        jMenuItemNoviNastup = new javax.swing.JMenuItem();
        jMenuItemIzmeniNastup = new javax.swing.JMenuItem();
        jMenuItemPrikaziNastupe = new javax.swing.JMenuItem();
        jMenuIzvodjaci = new javax.swing.JMenu();
        jMenuOsobeIzvodjaci = new javax.swing.JMenu();
        jMenuItemNoviOsobaIzvodjac = new javax.swing.JMenuItem();
        jMenuItemIzmeniOsobaIzvodjac = new javax.swing.JMenuItem();
        jMenuBendovi = new javax.swing.JMenu();
        jMenuItemNoviBend = new javax.swing.JMenuItem();
        jMenuItemIzmeniBend = new javax.swing.JMenuItem();
        jMenuMenadzment = new javax.swing.JMenu();
        jMenuItemNoviNalog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuNastup.setText("Nastup");

        jMenuItemNoviNastup.setText("Novi");
        jMenuNastup.add(jMenuItemNoviNastup);

        jMenuItemIzmeniNastup.setText("Izmeni");
        jMenuNastup.add(jMenuItemIzmeniNastup);

        jMenuItemPrikaziNastupe.setText("Prikazi");
        jMenuNastup.add(jMenuItemPrikaziNastupe);

        jMenuBar1.add(jMenuNastup);

        jMenuIzvodjaci.setText("Izvodjaci");

        jMenuOsobeIzvodjaci.setText("Osobe");

        jMenuItemNoviOsobaIzvodjac.setText("Novi ");
        jMenuItemNoviOsobaIzvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviOsobaIzvodjacActionPerformed(evt);
            }
        });
        jMenuOsobeIzvodjaci.add(jMenuItemNoviOsobaIzvodjac);

        jMenuItemIzmeniOsobaIzvodjac.setText("Izmeni");
        jMenuItemIzmeniOsobaIzvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzmeniOsobaIzvodjacActionPerformed(evt);
            }
        });
        jMenuOsobeIzvodjaci.add(jMenuItemIzmeniOsobaIzvodjac);

        jMenuIzvodjaci.add(jMenuOsobeIzvodjaci);

        jMenuBendovi.setText("Bendovi");

        jMenuItemNoviBend.setText("Novi");
        jMenuBendovi.add(jMenuItemNoviBend);

        jMenuItemIzmeniBend.setText("Izmeni");
        jMenuBendovi.add(jMenuItemIzmeniBend);

        jMenuIzvodjaci.add(jMenuBendovi);

        jMenuBar1.add(jMenuIzvodjaci);

        jMenuMenadzment.setText("Menadzment");

        jMenuItemNoviNalog.setText("Novi Nalog");
        jMenuItemNoviNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviNalogActionPerformed(evt);
            }
        });
        jMenuMenadzment.add(jMenuItemNoviNalog);

        jMenuBar1.add(jMenuMenadzment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNoviNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviNalogActionPerformed
        new FMenadzer(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemNoviNalogActionPerformed

    private void jMenuItemNoviOsobaIzvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviOsobaIzvodjacActionPerformed
        new FOsobaIzvodjac(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemNoviOsobaIzvodjacActionPerformed

    private void jMenuItemIzmeniOsobaIzvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzmeniOsobaIzvodjacActionPerformed
        new FOsobaIzvodjac(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemIzmeniOsobaIzvodjacActionPerformed

    private void prepareForm() {
        setLocationRelativeTo(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBendovi;
    private javax.swing.JMenuItem jMenuItemIzmeniBend;
    private javax.swing.JMenuItem jMenuItemIzmeniNastup;
    private javax.swing.JMenuItem jMenuItemIzmeniOsobaIzvodjac;
    private javax.swing.JMenuItem jMenuItemNoviBend;
    private javax.swing.JMenuItem jMenuItemNoviNalog;
    private javax.swing.JMenuItem jMenuItemNoviNastup;
    private javax.swing.JMenuItem jMenuItemNoviOsobaIzvodjac;
    private javax.swing.JMenuItem jMenuItemPrikaziNastupe;
    private javax.swing.JMenu jMenuIzvodjaci;
    private javax.swing.JMenu jMenuMenadzment;
    private javax.swing.JMenu jMenuNastup;
    private javax.swing.JMenu jMenuOsobeIzvodjaci;
    // End of variables declaration//GEN-END:variables
}
