/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import domain.DomainObject;
import java.awt.GridLayout;
import ui.components.iValue.IValue;
import ui.components.iValue.product.Product;

/**
 *
 * @author Aleksa
 */
public class FMain extends MyFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jbtnSave = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnFind = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNastup = new javax.swing.JMenu();
        jMenuItemNoviNastup = new javax.swing.JMenuItem();
        jMenuItemIzmeniNastup = new javax.swing.JMenuItem();
        jMenuItemPrikaziNastupe = new javax.swing.JMenuItem();
        jMenuIzvodjaci = new javax.swing.JMenu();
        jMenuOsobeIzvodjaci = new javax.swing.JMenu();
        jMenuItemNoviOsobaIzvodjac = new javax.swing.JMenuItem();
        jMenuItemIzmeniOsobaIzvodjac = new javax.swing.JMenuItem();
        jMenuBendovi = new javax.swing.JMenu();
        jMenuItemNoviBend = new javax.swing.JMenuItem();
        jMenuItemIzmeniBend = new javax.swing.JMenuItem();
        jMenuMenadzment = new javax.swing.JMenu();
        jMenuItemNoviNalog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jbtnSave.setText("Save");

        jbtnUpdate.setText("Update");

        jbtnDelete.setText("Delete");

        jbtnFind.setText("Find");

        jMenuNastup.setText("Nastup");

        jMenuItemNoviNastup.setText("Novi");
        jMenuNastup.add(jMenuItemNoviNastup);

        jMenuItemIzmeniNastup.setText("Izmeni");
        jMenuNastup.add(jMenuItemIzmeniNastup);

        jMenuItemPrikaziNastupe.setText("Prikazi");
        jMenuNastup.add(jMenuItemPrikaziNastupe);

        jMenuBar1.add(jMenuNastup);

        jMenuIzvodjaci.setText("Izvodjaci");

        jMenuOsobeIzvodjaci.setText("Osobe");

        jMenuItemNoviOsobaIzvodjac.setText("Novi ");
        jMenuItemNoviOsobaIzvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviOsobaIzvodjacActionPerformed(evt);
            }
        });
        jMenuOsobeIzvodjaci.add(jMenuItemNoviOsobaIzvodjac);

        jMenuItemIzmeniOsobaIzvodjac.setText("Izmeni");
        jMenuItemIzmeniOsobaIzvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzmeniOsobaIzvodjacActionPerformed(evt);
            }
        });
        jMenuOsobeIzvodjaci.add(jMenuItemIzmeniOsobaIzvodjac);

        jMenuIzvodjaci.add(jMenuOsobeIzvodjaci);

        jMenuBendovi.setText("Bendovi");

        jMenuItemNoviBend.setText("Novi");
        jMenuBendovi.add(jMenuItemNoviBend);

        jMenuItemIzmeniBend.setText("Izmeni");
        jMenuBendovi.add(jMenuItemIzmeniBend);

        jMenuIzvodjaci.add(jMenuBendovi);

        jMenuBar1.add(jMenuIzvodjaci);

        jMenuMenadzment.setText("Menadzment");

        jMenuItemNoviNalog.setText("Novi Nalog");
        jMenuItemNoviNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviNalogActionPerformed(evt);
            }
        });
        jMenuMenadzment.add(jMenuItemNoviNalog);

        jMenuBar1.add(jMenuMenadzment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDelete)
                            .addComponent(jbtnUpdate)
                            .addComponent(jbtnFind))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNoviNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviNalogActionPerformed
        new FMenadzer(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemNoviNalogActionPerformed

    private void jMenuItemNoviOsobaIzvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviOsobaIzvodjacActionPerformed
        new FOsobaIzvodjac(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemNoviOsobaIzvodjacActionPerformed

    private void jMenuItemIzmeniOsobaIzvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzmeniOsobaIzvodjacActionPerformed
        new FOsobaIzvodjac(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemIzmeniOsobaIzvodjacActionPerformed

    private void prepareForm() {
        setLocationRelativeTo(null);
        panel.setLayout(new GridLayout(1, 1));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBendovi;
    private javax.swing.JMenuItem jMenuItemIzmeniBend;
    private javax.swing.JMenuItem jMenuItemIzmeniNastup;
    private javax.swing.JMenuItem jMenuItemIzmeniOsobaIzvodjac;
    private javax.swing.JMenuItem jMenuItemNoviBend;
    private javax.swing.JMenuItem jMenuItemNoviNalog;
    private javax.swing.JMenuItem jMenuItemNoviNastup;
    private javax.swing.JMenuItem jMenuItemNoviOsobaIzvodjac;
    private javax.swing.JMenuItem jMenuItemPrikaziNastupe;
    private javax.swing.JMenu jMenuIzvodjaci;
    private javax.swing.JMenu jMenuMenadzment;
    private javax.swing.JMenu jMenuNastup;
    private javax.swing.JMenu jMenuOsobeIzvodjaci;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnFind;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnSave() {
        return jbtnSave;
    }

    public javax.swing.JButton getJbtnDelete() {
        return jbtnDelete;
    }

    public javax.swing.JButton getJbtnFind() {
        return jbtnFind;
    }

    public javax.swing.JButton getJbtnUpdate() {
        return jbtnUpdate;
    }

    @Override
    public Product getPanel() {
        return (Product) panel;
    }

    //nisam siguran ali bi trebalo da radi
    @Override
    public void fillForm(DomainObject domainObject) {
        ((IValue)panel).setValue(domainObject);
    }
    
}
