/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.panel.impl;

import domain.VrstaIzvodjaca;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import ui.components.IValue;

/**
 *
 * @author Aleksa
 */
public class inputPanelVrstaIzvodjaca extends javax.swing.JPanel implements IValue {

    private DefaultListModel<VrstaIzvodjaca> model;

    /**
     * Creates new form inputPanelVrstaIzvodjaca
     */
    public inputPanelVrstaIzvodjaca() {
        initComponents();
        prepareJlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxVrsteIzvodjaca = new javax.swing.JComboBox<>();
        jbtnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOdabraneVrste = new javax.swing.JList<>();

        jLabel1.setText("Vrste izvodjaca:");

        jbtnDodaj.setText("Dodaj");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListOdabraneVrste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVrsteIzvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxVrsteIzvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        VrstaIzvodjaca vrstaIzvodjaca = (VrstaIzvodjaca) jComboBoxVrsteIzvodjaca.getSelectedItem();
        model.addElement(vrstaIzvodjaca);
    }//GEN-LAST:event_jbtnDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<VrstaIzvodjaca> jComboBoxVrsteIzvodjaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<VrstaIzvodjaca> jListOdabraneVrste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        List<VrstaIzvodjaca> output = new ArrayList<VrstaIzvodjaca>();
        for (int i = 0; i < jListOdabraneVrste.getModel().getSize(); i++) {
            output.add(jListOdabraneVrste.getModel().getElementAt(i));
        }
        return output;
    }

    /**
     *Ubacivanje u jlistu
     * @param List<VrstaIzvodjaca> value
     */
    @Override
    public void setValue(Object value) {
        if (value == null) {
            return;
        }
        if (!(value instanceof List)) {
            System.out.println("Nije ubacena lista!!!");
            return;
        }
        List<VrstaIzvodjaca> vrste = (List<VrstaIzvodjaca>) value;
        for (VrstaIzvodjaca vrstaIzvodjaca : vrste) {
            model.addElement(vrstaIzvodjaca);
        }
//        jListOdabraneVrste = new JList<VrstaIzvodjaca>(model);
    }

    /**
     *Ubacivanje u combo box
     * @param List<VrstaIzvodjaca> initValue
     */
    @Override
    public void inicialize(Object initValue) {
        if (initValue == null) {
            return;
        }
        if (!(initValue instanceof List)) {
            System.out.println("Nije ubacena lista!!!");
            return;
        }
        List<VrstaIzvodjaca> lista = (List<VrstaIzvodjaca>) initValue;

        for (VrstaIzvodjaca vrstaIzvodjaca : lista) {
            jComboBoxVrsteIzvodjaca.addItem(vrstaIzvodjaca);
        }
    }

    private void prepareJlist() {
        model = new DefaultListModel<>();
        jListOdabraneVrste = new JList<>(model);
        jListOdabraneVrste.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jListOdabraneVrste.setCellRenderer(new DefaultListCellRenderer() {
            JLabel rv = new JLabel();
            @Override
            public Component getListCellRendererComponent(JList list,
                    Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                String s = (value != null && value instanceof VrstaIzvodjaca) ? ((VrstaIzvodjaca) value).toString() : "";
                rv.setText(s);
                if (isSelected) {
                    rv.setBackground(list.getSelectionBackground());
                    rv.setForeground(list.getSelectionForeground());
                } else {
                    rv.setBackground(list.getBackground());
                    rv.setForeground(list.getForeground());
                }
                rv.setEnabled(list.isEnabled());
                rv.setFont(list.getFont());
                rv.setOpaque(true);
                return rv;
            }
        });
    }
}
