/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.panel.impl;

import java.util.Arrays;
import javax.swing.JCheckBox;
import ui.components.IValue;

/**
 *
 * @author Aleksa
 */
public class PanelOsobaIzvodjac extends javax.swing.JPanel implements IValue{

    /**
     * Creates new form PanelOsobaIzvodjac
     */
    public PanelOsobaIzvodjac() {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanelIdOsobaIzvodjac = new ui.components.panel.impl.InputPanelTextField();
        inputPanelIme = new ui.components.panel.impl.InputPanelTextField();
        inputPanelPrezime = new ui.components.panel.impl.InputPanelTextField();
        inputPanelTelefon = new ui.components.panel.impl.InputPanelTextField();
        inputPanelEmail = new ui.components.panel.impl.InputPanelTextField();
        inputPanelPol = new ui.components.panel.impl.InputPanelComboBox();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPanelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanelIdOsobaIzvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inputPanelPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPanelIdOsobaIzvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputPanelIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputPanelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanelPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.panel.impl.InputPanelTextField inputPanelEmail;
    private ui.components.panel.impl.InputPanelTextField inputPanelIdOsobaIzvodjac;
    private ui.components.panel.impl.InputPanelTextField inputPanelIme;
    private ui.components.panel.impl.InputPanelComboBox inputPanelPol;
    private ui.components.panel.impl.InputPanelTextField inputPanelPrezime;
    private ui.components.panel.impl.InputPanelTextField inputPanelTelefon;
    // End of variables declaration//GEN-END:variables

    private void preparePanel() {
        
        inputPanelIme.getJlabText().setText("Ime:");
        inputPanelIme.getJlabError().setText("");
        inputPanelIme.getJtxtInput().setText("");
        inputPanelPrezime.getJlabText().setText("Prezime:");
        inputPanelPrezime.getJlabError().setText("");
        inputPanelPrezime.getJtxtInput().setText("");
        inputPanelTelefon.getJlabText().setText("Telefon:");
        inputPanelTelefon.getJlabError().setText("");
        inputPanelTelefon.getJtxtInput().setText("");
        inputPanelEmail.getJlabText().setText("Email:");
        inputPanelEmail.getJlabError().setText("");
        inputPanelEmail.getJtxtInput().setText("");
        inputPanelPol.getJlabText().setText("Pol:");
        inputPanelPol.getJlabError().setText("");
        inputPanelPol.inicialize(Arrays.asList(new String[]{"MALE","FEMALE","OTHER"}));
        
        //refactor:
//        jComboBoxVrstaIzvodjaca.addItem(new JCheckBox("aleksa", true));
//        jComboBoxVrstaIzvodjaca.addItem(new JCheckBox("dojcilo", false));
//        jComboBoxVrstaIzvodjaca.addItem(new JCheckBox("nada", true));
    }

    @Override
    public Object getValue() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setValue(Object value) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void inicialize(Object initValue) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
