/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.product.impl;

import domain.Menadzer;
import domain.Pol;
import java.util.Arrays;
import ui.components.iValue.IValue;
import ui.components.iValue.product.Product;

/**
 *
 * @author Aleksa
 */
public class PanelMenadzer extends Product implements IValue{

    /**
     * Creates new form PanelMenadzer
     */
    public PanelMenadzer() {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanelIdMenadzer = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelUserName = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelPassword = new ui.components.iValue.impl.InputPanelPassword();
        inputPanelPasswordCheck = new ui.components.iValue.impl.InputPanelPassword();
        inputPanelIme = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelPrezime = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelTelefon = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelEmail = new ui.components.iValue.impl.InputPanelTextField();
        inputPanelPol = new ui.components.iValue.impl.InputPanelComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Menadzer"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanelIdMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(inputPanelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputPanelIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputPanelPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputPanelPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputPanelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanelIdMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputPanelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanelPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inputPanelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.iValue.impl.InputPanelTextField inputPanelEmail;
    private ui.components.iValue.impl.InputPanelTextField inputPanelIdMenadzer;
    private ui.components.iValue.impl.InputPanelTextField inputPanelIme;
    private ui.components.iValue.impl.InputPanelPassword inputPanelPassword;
    private ui.components.iValue.impl.InputPanelPassword inputPanelPasswordCheck;
    private ui.components.iValue.impl.InputPanelComboBox inputPanelPol;
    private ui.components.iValue.impl.InputPanelTextField inputPanelPrezime;
    private ui.components.iValue.impl.InputPanelTextField inputPanelTelefon;
    private ui.components.iValue.impl.InputPanelTextField inputPanelUserName;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        Menadzer menadzer;
        Long idMenadzer = Long.parseLong((String)inputPanelIdMenadzer.getValue());
        String username = (String)inputPanelUserName.getValue();
        String password = (String)inputPanelPassword.getValue();
        String imeMenadzera = (String)inputPanelIme.getValue();
        String prezimeMenadzera = (String)inputPanelPrezime.getValue();
        String telefon = (String)inputPanelTelefon.getValue();
        String email = (String)inputPanelEmail.getValue();
        Pol pol = Pol.valueOf((String)inputPanelPol.getValue());
        
        menadzer = new Menadzer(idMenadzer, username, password, imeMenadzera, prezimeMenadzera, telefon, email, pol);
        
        return menadzer;
    }

    @Override
    public void setValue(Object value) {
        if (value instanceof Menadzer) {
            Menadzer menadzer = (Menadzer) value;
            
            inputPanelIdMenadzer.setValue(menadzer.getIdMenadzer());
            inputPanelUserName.setValue(menadzer.getUsername());
            inputPanelPassword.setValue(menadzer.getPassword());
            inputPanelIme.setValue(menadzer.getIdMenadzer());
            inputPanelPrezime.setValue(menadzer.getPrezimeMenadzera());
            inputPanelTelefon.setValue(menadzer.getTelefon());
            inputPanelEmail.setValue(menadzer.getEmail());
            inputPanelPol.setValue(menadzer.getPol());
        }else {
            System.out.println("Niste ubacili menadzera");
        }
    }

    @Override
    public void inicialize(Object initValue) {
        if (initValue instanceof Menadzer) {
            Menadzer menadzer = (Menadzer) initValue;
            
            inputPanelIdMenadzer.setValue(menadzer.getIdMenadzer());
            inputPanelUserName.setValue(menadzer.getUsername());
            inputPanelPassword.setValue(menadzer.getPassword());
            inputPanelIme.setValue(menadzer.getIdMenadzer());
            inputPanelPrezime.setValue(menadzer.getPrezimeMenadzera());
            inputPanelTelefon.setValue(menadzer.getTelefon());
            inputPanelEmail.setValue(menadzer.getEmail());
            inputPanelPol.setValue(menadzer.getPol());
        }else {
            System.out.println("Niste ubacili menadzera");
        }
    }

    public ui.components.iValue.impl.InputPanelComboBox getInputPanelComboBox1() {
        return inputPanelPol;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelEmail() {
        return inputPanelEmail;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelIdMenadzer() {
        return inputPanelIdMenadzer;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelIme() {
        return inputPanelIme;
    }

    public ui.components.iValue.impl.InputPanelPassword getInputPanelPassword() {
        return inputPanelPassword;
    }

    public ui.components.iValue.impl.InputPanelPassword getInputPanelPasswordCheck() {
        return inputPanelPasswordCheck;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelPrezime() {
        return inputPanelPrezime;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelTelefon() {
        return inputPanelTelefon;
    }

    public ui.components.iValue.impl.InputPanelTextField getInputPanelUserName() {
        return inputPanelUserName;
    }

    private void preparePanel() {
        inputPanelIdMenadzer.getJlabText().setText("ID Menadzera:");
        inputPanelIdMenadzer.getJlabError().setText("");
        inputPanelIdMenadzer.getJtxtInput().setText("");
        inputPanelUserName.getJlabText().setText("Username:");
        inputPanelUserName.getJlabError().setText("");
        inputPanelUserName.getJtxtInput().setText("");
        inputPanelPassword.getJlabText().setText("Password:");
        inputPanelPassword.getJlabError().setText("");
        inputPanelPassword.getJpassword().setText("");
        inputPanelPasswordCheck.getJlabText().setText("Repeat Password:");
        inputPanelPasswordCheck.getJlabError().setText("");
        inputPanelPasswordCheck.getJpassword().setText("");
        inputPanelIme.getJlabText().setText("Ime:");
        inputPanelIme.getJlabError().setText("");
        inputPanelIme.getJtxtInput().setText("");
        inputPanelPrezime.getJlabText().setText("Prezime:");
        inputPanelPrezime.getJlabError().setText("");
        inputPanelPrezime.getJtxtInput().setText("");
        inputPanelTelefon.getJlabText().setText("Telefon:");
        inputPanelTelefon.getJlabError().setText("");
        inputPanelTelefon.getJtxtInput().setText("");
        inputPanelEmail.getJlabText().setText("Email:");
        inputPanelEmail.getJlabError().setText("");
        inputPanelEmail.getJtxtInput().setText("");
        inputPanelPol.getJlabText().setText("Pol:");
        inputPanelPol.getJlabError().setText("");
        inputPanelPol.inicialize(Arrays.asList(new String[]{"MALE","FEMALE","OTHER"}));
    }
    
    public Boolean validateMenadzer(){
        if (inputPanelPassword.getValue().equals(inputPanelPasswordCheck.getValue())) {
            return true;
        }
        return  false;
    }
    
}
